apiVersion: batch/v1
kind: Job
metadata:
  name: create-databases
spec:
  template:
    spec:
      containers:
        - name: postgres

          image: postgres:latest
          command: ["sh", "-c", "psql -h $HOST -U $POSTGRES_USER -d mydatabase -c '\\l'"]
#          command: ["sh", "-c", "psql -h $HOST -U $POSTGRES_USER -d mydatabase -c 'CREATE DATABASE backendoneDb;'"]
          env:
            - name: POSTGRES_USER
              value: "test"
            - name: PGPASSWORD
              value: "K#gn$9}fW8m*?s61`isg2)Xdq*Ni+0EK"
            - name: HOST
              value: "myeksauroraclusterstack-databaseb269d8bb-0td9vu421zqy.cluster-c117odnd1k38.eu-north-1.rds.amazonaws.com"
      restartPolicy: Never
  backoffLimit: 4
#spec:
#  template:
#    spec:
#      containers:
#        - name: db-init
#          image: postgres:17
#          command: ["sh", "-c"]
#          args:
#            - |
#              PGPASSWORD='K#gn$9}fW8m*?s61`isg2)Xdq*Ni+0EK' psql -h myeksauroraclusterstack-databaseb269d8bb-0td9vu421zqy.cluster-c117odnd1k38.eu-north-1.rds.amazonaws.com -U test -c '\l'
#              PGPASSWORD='K#gn$9}fW8m*?s61`isg2)Xdq*Ni+0EK' psql -h myeksauroraclusterstack-databaseb269d8bb-0td9vu421zqy.cluster-c117odnd1k38.eu-north-1.rds.amazonaws.com -U test postgres <<EOF
#              CREATE DATABASE backendoneDb;
#              CREATE DATABASE backendtwoDb;
#              EOF
#          env:
#            - name: PGPASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: your-db-secret
#                  key: password
#      restartPolicy: Never
#  backoffLimit: 4
  