apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendone
  labels:
    app: backendone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendone
  template:
    metadata:
      name: backendone
      labels:
        app: backendone
    spec:
      containers:
        - name: backendone
          image: backendone:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '3000'
      restartPolicy: Always
      