apiVersion: apps/v1
kind: Deployment
metadata:
  name: techjumpfront
  labels:
    app: techjumpfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techjumpfront
  template:
    metadata:
      name: techjumpfront
      labels:
        app: techjumpfront
    spec:
      containers:
        - name: techjumpfront
          image: techjumpfront:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: techjumpfront-config
      restartPolicy: Always
      