apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.needMigration }}
      initContainers:
        - name: db-migration
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          command: [ "npm" ]
          args: [ "run", "migrate:up" ]
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            {{- end }}

      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "{{ .Values.port }}"
          {{- if .Values.includeConfigMap }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
                {{- end }}
      restartPolicy: Always