apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.projectName}}-db-secrets
type: Opaque
data:
  DB_USER: {{ .Values.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc | quote }}