name: Build and Push
description: This action builds and push artifacts to ECR registry
runs:
  using: composite
  steps:
    - name: Set up node and npm
      uses: ./.github/actions/setup-node-npm
    - name: lerna cache
      uses: ./.github/actions/restore-lerna-cache
    - name: Prepare Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-north-1
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
    - name: Set environment variables
      shell: bash
      run: |
        echo "DOCKER_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
    - name: build app
      shell: bash
      run: lerna run build
    - name: prepare docker images
      shell: bash
      run: lerna run docker-build
    - name: push docker image
      shell: bash
      run: lerna run docker-push
    - name: save lerna cache
      uses: ./.github/actions/save-lerna-cache
