global:
  defaultStorageClass: gp2
  postgresql:
    auth:
      username: admin
      password: admin
      database: mydatabase
primary:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2