name: Prepare infra with aurora

on:
  workflow_dispatch:

jobs:
  create_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare AWS
        id: prepare-aws
        uses: ./.github/actions/prepare-aws-utils
        with:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: 'eu-north-1'
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CLUSTER_NAME: 'my-eks-aurora-cluster'
      - name: Set up env variables
        run: |
          echo "DOCKER_REGISTRY=${{ steps.prepare-aws.outputs.registry }}" >> $GITHUB_ENV
          echo "NAME_SPACE=default" >> $GITHUB_ENV
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: prepare infrastructure create docker registries
        run: lerna run prepare-infrastructure
      - name: Deploy EKS with Aurora Cluster
        run: lerna run deploy:eks-aurora-stack
      - name: Retrieve secrets from AWS Secrets Manager
        id: get_secrets
        run: |
            SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id eks-aurora-secret --query SecretString --output text)
            echo "::set-output name=DB_USER::$(echo $SECRET_JSON | jq -r '.username')"
            echo "::set-output name=DB_PASSWORD::$(echo $SECRET_JSON | jq -r '.password')"
            echo "::set-output name=DB_HOST::$(echo $SECRET_JSON | jq -r '.host')"
      - name: Apply secretes
        run : lerna run apply:secrets
      - name: Apply config maps
        run : lerna run apply:configmap
      - name: Run kubernetes job for table creations
        run: lerna run infra:helm:deploy:database-job
      - name: Run deployments to the cluster
        run: lerna run deploy:backend
      - name: Deploy frontend app
        run: lerna run deploy:app
      - name: Build and push app
        uses: ./.github/actions/build-and-push
      - name: Rollout changes
        run: lerna run rollout:changes
    
        

