name: Pull request
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        description: "Pull request number"
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: false

jobs:
  destroy-pr-infrastructure:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: Added namespace value to the scope
        run: echo "NAME_SPACE=pr-${{ env.REPOSITORY_NAME }}-test" >> $GITHUB_ENV
      - name: lerna cache
        uses: ./.github/actions/restore-lerna-cache
      - name: Prepare Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER }}
      - name: Delete docker  registry
        run: lerna run destroy-registry
      - name: Destroy CDK stack
        run: lerna run destroy-infrastructure
      - name: delete kubernetes services, deployments
        run: |
          kubectl delete deployments,services --all ${{env.NAME_SPACE}} 
          kubectl delete namespace ${{env.NAME_SPACE}} 



