name: Pull request
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
        description: "Pull request number"
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: false

jobs:
  destroy-pr-infrastructure:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Cashing npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install dependencies
        run: npm ci
      - name: lerna cache
        uses: ./github/workflows/lerna-cache.yml
      - name: Prepare Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
      - name: Destroy registry
        run: npx lerna run destroy-infrastructure




