name: Pull request
on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check package lock
        run: ls
      - name: Cashing npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install dependencies
        run: npm ci
      - name: test scripts
        run: lerna run test
      - name: build app
        run: lerna run build
      - name: artifacts
        run:  echo 'something with artifacts!'
      - name: deploy app
        run: echo 'DEPLOYING !!!!!!1111'


