name: Pull request

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build app
        run: lerna run build


