name: Pull request
on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check package lock
        run: ls
      - name: Cashing npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: lerna cache
        id: lerna-cache
        uses: actions/cache/restore@v4
        with:
          path: lerna/cache
          key: ${{ runner.os }}-lerna-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-main-
      - name: log  hasFile
        run: echo this hash ${{ hashFiles('lerna/**/*') }}
      - name: install dependencies
        run: npm ci
      - name: run scripts to test lerna cache
        run: lerna run blocker
      - name: test scripts
        run: lerna run test
      - name: build app
        run: lerna run build
      - name: artifacts
        run:  echo 'something with artifacts!'
      - name: deploy app
        run: echo 'DEPLOYING !!!!!!1111'
      - name: log  hasFile again
        run: echo this hash ${{ hashFiles('lerna/**/*') }}
      - name: update cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: lerna/cache
          key: ${{steps.lerna-cache.outputs.cache-primary-key}}



