name: Build PR
on:
  pull_request:
    types: [synchronize]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    steps:
      - name: Build and push app
        uses: ./.github/actions/build-and-push





