name: Build PR
on:
  pull_request:
    types: [synchronize]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare AWS
        id: prepare-aws
        uses: ./.github/actions/prepare-aws-utils
        with:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: 'eu-north-1'
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CLUSTER_NAME: ${{ vars.EKS_CLUSTER }}
      - name: Set up env variables
        run: |
          echo "DOCKER_REGISTRY=${{ steps.prepare-aws.outputs.registry }}" >> $GITHUB_ENV
          echo "NAME_SPACE=pr-${{ env.REPOSITORY_NAME }}-test" >> $GITHUB_ENV
      - name: Build and push app
        uses: ./.github/actions/build-and-push
      - name: Rollout changes
        run : lerna run rollout:changes
