name: prepare-pr-infra
on:
  pull_request:
    types: [opened, reopened]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: true
jobs:
  prepair_infra:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: restore lerna cache
        uses: ./.github/actions/restore-lerna-cache
      - name: Prepare Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
      - name: prepare infrastructure
        run: lerna run prepare-infrastructure
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Set environment variables
        run: |
          echo "DOCKER_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER }}
      - name: Added namespace value to the scope
        run: echo "NAME_SPACE=pr-${{ env.REPOSITORY_NAME }}-test" >> $GITHUB_ENV
      - name: Prepare deployments
        run: lerna run infra:create:namespace
      - name: Apply config maps
        run: lerna run apply:configmap
      - name: Run deployments to the cluster
        run: lerna run deploy:backend
      - name: Update config map backends dns names
        run: lerna run update:configmap
      - name: Deploy frontend app
        run: lerna run deploy:app
      - name: Run change images in config maps
        run: lerna run update:image
      - name: save lerna cache
        uses: ./.github/actions/save-lerna-cache
  build-app:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and push app
        uses: ./.github/actions/build-and-push
        with:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: 'eu-north-1'
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

