name: prepare-pr-infra
on:
  pull_request:
    types: [opened, reopened]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: true
jobs:
  prepare_infra:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: restore lerna cache
        uses: ./.github/actions/restore-lerna-cache
      - name: Prepare AWS
        id: prepare-aws
        uses: ./.github/actions/prepare-aws-utils
        with:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: 'eu-north-1'
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CLUSTER_NAME: ${{ vars.EKS_CLUSTER }}
      - name: Set up env variables
        run: |
          echo "DOCKER_REGISTRY=${{ steps.prepare-aws.outputs.registry }}" >> $GITHUB_ENV
          echo "NAME_SPACE=pr-${{ env.REPOSITORY_NAME }}-test" >> $GITHUB_ENV
      - name: prepare infrastructure
        run: lerna run prepare-infrastructure
      - name: Apply config maps
        run: lerna run apply:configmap
      - name: Run deployments to the cluster
        run: lerna run deploy:backend
      - name: Update config map backends dns names
        run: lerna run update:configmap
      - name: Deploy frontend app
        run: lerna run deploy:app
      - name: Run change images in config maps
        run: lerna run update:image
      - name: save lerna cache
        uses: ./.github/actions/save-lerna-cache
  build-app:
    runs-on: ubuntu-latest
    needs: prepare_infra
    env:
      REPOSITORY_NAME: ${{ github.event.pull_request.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Prepare AWS
        id: prepare-aws
        uses: ./.github/actions/prepare-aws-utils
        with:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_REGION: 'eu-north-1'
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CLUSTER_NAME: ${{ vars.EKS_CLUSTER }}
      - name: Set up env variables
        run: |
          echo "DOCKER_REGISTRY=${{ steps.prepare-aws.outputs.registry }}" >> $GITHUB_ENV
      - name: Build and push app
        uses: ./.github/actions/build-and-push


