name: prepare-pr-infra
on:
  pull_request:
    types: [opened,reopened]
concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: true

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Running scripts for PR
        run: echo "Im running test"
      - name: I want to sleep too
        run: sleep 5
      - name: I slept well!
        run: echo "I slept well!"