name: PR Updated
on:
  pull_request:
    types: [synchronize]
  workflow_run:
    workflows: ["pull-request-opened"]
    types:
      - completed

concurrency:
  group: ${{ github.head_ref || github.run_id }}-pr
  cancel-in-progress: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Running scripts for PR updated1!
        run: echo "Im running"
      - name: I want to sleep too
        run: sleep 5
      - name: I slept well!
        run: echo "I slept well!"


