name: Publish packages
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write

jobs:
  run-scripts-versioning:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_VER }}
      NODE_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_VER }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Cashing npm and set up publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kayuaga'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: lerna cache
        id: lerna-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            lerna/cache
            packages/*/dist
          key:  cache-${{ runner.os }}-lerna-main-
          restore-keys: |
            cache-${{ runner.os }}-lerna-${{ github.ref_name }}
      - name: github creds
        run: git config --global user.email "test@test.com"
          && git config --global user.name "test"
      - name: lerna publish
        run: npx lerna publish --yes --conventional-commits --no-private
