name: Publish packages
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write

jobs:
  run-scripts-versioning:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_VER }}
      NODE_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_VER }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: restore lerna cache
        uses: ./.github/actions/restore-lerna-cache
      - name: github credentials
        run: git config --global user.email "test@test.com"
          && git config --global user.name "test"
      - name: lerna publish
        run: npx lerna publish from-package --yes --conventional-commits --no-private
