name: Reset cache

on:
  workflow_dispatch:

jobs:
  run-scripts-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up node and npm
        uses: ./.github/actions/setup-node-npm
      - name: install deps
        run: npm ci
      - name: nx reset
        run: npx nx reset
      - name: make new lerna cache
        uses: ./.github/actions/save-lerna-cache


