name: versioning.yml
on:
  workflow_dispatch:


jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check package lock
        run: ls
      - name: Cashing npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install deps
        run: npm ci
      - name: lerna version
        run: lerna version --yes --conventional-commits
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

