name: versioning.yml
on:
  workflow_dispatch:
permissions:
    id-token: write
    contents: write


jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check package lock
        run: ls
      - name: Cashing npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install deps
        run: npm ci
      - name: lerna cache
        id: lerna-cache
        uses: actions/cache/restore@v4
        with:
          path: lerna/cache
          key: cache-${{ github.run_id  }}
          restore-keys: |
            ${{ runner.os }}-lerna-${{ github.ref_name }}
            ${{ runner.os }}-lerna-main-
      - name: github creds
        run: git config --global user.email "test@test.com" 
             & git config --global user.name "test"
      - name: cheking secret
        run: echo ${{ secrets.REPO_ACCESS_VER }}
      - name: lerna version
        run: lerna version --yes --conventional-commits
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_VER }}
      - name: update cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: lerna/cache
          key: ${{ runner.os }}-lerna-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('lerna/cache') }}

