name: Restore lerna cache
description: This action restores lerna's cache
runs:
  using: composite
  steps:
    - name: Restore cache
      shell: bash
      id: lerna-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          lerna/cache
          packages/*/dist
          projects/*/build
          projects/*/.next
        key: cache-${{ github.run_id  }}
        restore-keys: |
          ${{ runner.os }}-lerna-${{ github.ref_name }}
          ${{ runner.os }}-lerna-main-
